services:
  mysql:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tacobank_db
    ports:
      - "3700:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - tacobank

  auth-server:
    build: ./backend/auth_server
    container_name: auth_server
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - tacobank

  business-server:
    build: ./backend/business_server
    container_name: business_server
    ports:
      - "8081:8081"
    depends_on:
      - mariadb
    networks:
      - tacobank

  ai-server:
    build: ./backend/ai_server
    container_name: ai_server
    ports:
      - "8082:8082"
    depends_on:
      - mariadb
    networks:
      - tacobank

  frontend:
    build: ./frontend/react
    container_name: front
    ports:
      - "5173:5173"
    networks:
      - tacobank

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - tacobank

  nginx:
    build: ./api_gateway
    container_name: api_gateway
    ports:
      - "80:80"
    depends_on:
      auth-server:
        condition: service_started
      business-server:
        condition: service_started
      ai-server:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - tacobank

volumes:
  mariadb_data:

networks:
  tacobank:
    driver: bridge

# docker rmi -f $(docker images -q) - 모든이미지 삭제
# docker rm $(docker ps -aq) - 모든 컨테이너 삭제
# docker network prune -f - 기본 네트워크 제외 모든 네트워크 삭제
# docker-compose up -d --build -  빌드 후 실행
# docker-compose down - 실행중지