spring:
  application:
    name: email_server
  datasource:
    url: jdbc:mariadb://localhost:3306/tacobank_db
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  data:
    redis:
#      host: redis
      host: localhost
      port: 6379

server:
  port: 8083