global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100'] # 시스템 메트릭(CPU 사용량, 메모리, 디스크 IO 등)

  - job_name: 'nginx_exporter' # gateway 감시
    static_configs:
      - targets: ['nginx_exporter:9113']

  - job_name: 'nginx_log_exporter' # 로그감시
    static_configs:
      - targets: ['nginx_log_exporter:4040']
