spring:
  application:
    name: business_server
  datasource:
    url: jdbc:mariadb://localhost:3306/tacobank_db
    username: root
    password: 123123
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      #      host: redis
      host: localhost
      port: 6379

server:
  port: 8081
